
from __future__ import annotations

import argparse
import os
from pathlib import Path

os.environ.setdefault(
    "MPLCONFIGDIR",
    str(Path(__file__).resolve().parent / ".matplotlib-cache"),
)

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LinearSegmentedColormap, Normalize
import numpy as np
import torch

from evaluation import evaluate_gpcreg as evaluation


# Plotly "blackbody"-inspired scale used by the original visualization,
# with the white stop removed so that points remain visible on white pages.
BLACKBODY_NO_WHITE = LinearSegmentedColormap.from_list(
    "blackbody_no_white",
    [
        (0.00, "#000000"),
        (0.25, "#e60000"),
        (0.55, "#e6d200"),
        (1.00, "#80b7ff"),
    ],
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Visualize low, moderate, and strong ModelNet10 registration "
            "examples."
        )
    )
    parser.add_argument("--data_root", default="ModelNet10")
    parser.add_argument(
        "--deftransnet_ckpt",
        default="DeftransNet.pth",
    )
    parser.add_argument(
        "--gpc_ckpt",
        default="Registration/gpcreg/seed_42/Saves/epoch_20.pth",
    )
    parser.add_argument(
        "--gpc_script",
        default="training/train_gpcreg.py",
    )
    parser.add_argument(
        "--sample_name",
        default="desk_0202.off",
        help="The single ModelNet10 test object shown in all three rows.",
    )
    parser.add_argument(
        "--levels",
        nargs=3,
        type=float,
        default=(0.2, 0.5, 0.8),
        metavar=("LOW", "MODERATE", "STRONG"),
    )
    parser.add_argument(
        "--base_seed",
        type=int,
        default=42,
        help="Base seed used for sampling, TPS deformation, and target shuffle.",
    )
    parser.add_argument(
        "--display",
        choices=("gpc", "deftransnet", "both"),
        default="gpc",
        help=(
            "'gpc' reproduces the three-column reference layout; "
            "'both' adds the DefTransNet result as a fourth column."
        ),
    )
    parser.add_argument(
        "--output",
        default=(
            "Registration/Evaluation/GPC_Reg_Final/"
            "eval_modelnet10_registration_examples_low_mid_high.pdf"
        ),
    )
    parser.add_argument("--device", default=None)
    parser.add_argument("--num_patches", type=int, default=32)
    parser.add_argument("--patch_size", type=int, default=24)
    parser.add_argument("--token_dim", type=int, default=128)
    parser.add_argument("--num_geo_blocks", type=int, default=1)
    parser.add_argument("--refine_alpha", type=float, default=0.10)
    parser.add_argument("--elev", type=float, default=20.0)
    parser.add_argument("--azim", type=float, default=-60.0)
    return parser.parse_args()


def resolved(path_text: str) -> Path:
    return Path(os.path.expanduser(path_text)).resolve()


def create_same_sample_pairs(
    args: argparse.Namespace,
    gpc_module,
) -> list[dict]:
    data_root = resolved(args.data_root)
    if not data_root.is_dir():
        raise FileNotFoundError(f"ModelNet10 dataset not found: {data_root}")

    dataset = gpc_module.PointCloudData_ModelNet(
        data_root,
        folder="test",
        transform=gpc_module.train_transforms,
        typ=gpc_module.BENCHMARK_TRAIN_TYPES,
        rotation=gpc_module.rotation,
    )
    matching_indices = [
        index
        for index, item in enumerate(dataset.files)
        if str(item["name"]) == args.sample_name
    ]
    if len(matching_indices) != 1:
        raise ValueError(
            f"Expected one test object named {args.sample_name!r}; "
            f"found {len(matching_indices)}."
        )

    dataset_index = matching_indices[0]
    sample_seed = args.base_seed + dataset_index

    # Sample and normalize the source once. The target generated by this
    # dataset call is discarded because the three requested levels are
    # generated explicitly below.
    evaluation.set_all_seeds(sample_seed)
    sample = dataset[dataset_index]
    source = (
        sample["source_pointcloud"]
        .float()
        .unsqueeze(0)
        .cpu()
    )

    tps = gpc_module.TPS()
    pairs = []
    for level in args.levels:
        if not 0.0 < float(level) <= 1.0:
            raise ValueError(
                f"Deformation levels must lie in (0, 1], received {level}."
            )

        # Resetting the same seed makes the Gaussian control-point shift
        # identical up to multiplication by the deformation level.
        evaluation.set_all_seeds(sample_seed)
        target = (
            tps.fit(source.squeeze(0).clone(), float(level))
            .float()
            .unsqueeze(0)
            .cpu()
        )
        target_shuffled, permutation = evaluation.shuffle_target(
            target,
            sample_seed + 1,
        )
        pairs.append(
            {
                "dataset_index": dataset_index,
                "name": args.sample_name,
                "deformation_level": float(level),
                "sample_seed": sample_seed,
                "target_shuffle_seed": sample_seed + 1,
                "source": source.clone(),
                "target": target,
                "target_shuffled": target_shuffled.cpu(),
                "target_permutation": permutation.cpu(),
            }
        )
    return pairs


def build_models(
    args: argparse.Namespace,
    gpc_module,
    device: torch.device,
) -> tuple[torch.nn.Module | None, torch.nn.Module | None]:
    deftransnet = None
    gpc_reg = None

    if args.display in ("deftransnet", "both"):
        deftransnet = evaluation.benchmark_mod.DefTransNet(show=0)
        evaluation.load_state(
            deftransnet,
            resolved(args.deftransnet_ckpt),
            device,
            "DefTransNet",
            strict=True,
        )
        deftransnet = deftransnet.to(device).eval()

    if args.display in ("gpc", "both"):
        gpc_reg = gpc_module.GeoPatchDefTransNet(
            token_dim=args.token_dim,
            num_geo_blocks=args.num_geo_blocks,
            show=0,
            refine_alpha=args.refine_alpha,
        )
        evaluation.load_state(
            gpc_reg,
            resolved(args.gpc_ckpt),
            device,
            "GPC-Reg",
            strict=True,
        )
        gpc_reg = gpc_reg.to(device).eval()

    return deftransnet, gpc_reg


@torch.inference_mode()
def register_pair(
    pair: dict,
    deftransnet: torch.nn.Module | None,
    gpc_reg: torch.nn.Module | None,
    args: argparse.Namespace,
    gpc_module,
    device: torch.device,
) -> dict:
    source = pair["source"].to(device)
    target = pair["target"].to(device)
    target_shuffled = pair["target_shuffled"].to(device)

    source_np = source.squeeze(0).cpu().numpy()
    target_np = target.squeeze(0).cpu().numpy()
    initial_errors = (
        torch.linalg.norm(source - target, dim=-1)
        .squeeze(0)
        .cpu()
        .numpy()
    )

    result = {
        "name": str(pair["name"]),
        "level": float(pair["deformation_level"]),
        "source": source_np,
        "target": target_np,
        "initial_errors": initial_errors,
    }

    if deftransnet is not None:
        displacement, _, _ = evaluation.predict_benchmark(
            deftransnet,
            source,
            target_shuffled,
            device,
        )
        registered = source + displacement
        errors = torch.linalg.norm(
            registered - target,
            dim=-1,
        ).squeeze(0)
        result["def_registered"] = registered.squeeze(0).cpu().numpy()
        result["def_errors"] = errors.cpu().numpy()
        result["def_mean"] = float(errors.mean().item())

    if gpc_reg is not None:
        displacement, _, _ = evaluation.predict_gpc(
            gpc_reg,
            source,
            target_shuffled,
            args,
            gpc_module,
            device,
        )
        registered = source + displacement
        errors = torch.linalg.norm(
            registered - target,
            dim=-1,
        ).squeeze(0)
        result["gpc_registered"] = registered.squeeze(0).cpu().numpy()
        result["gpc_errors"] = errors.cpu().numpy()
        result["gpc_mean"] = float(errors.mean().item())

    return result


def style_coordinate_axis(
    axis,
    centre: np.ndarray,
    radius: float,
    elev: float,
    azim: float,
) -> None:
    axis.set_xlim(centre[0] - radius, centre[0] + radius)
    axis.set_ylim(centre[1] - radius, centre[1] + radius)
    axis.set_zlim(centre[2] - radius, centre[2] + radius)
    axis.set_box_aspect((1, 1, 1))
    axis.view_init(elev=elev, azim=azim)

    pane_color = (0.91, 0.93, 0.97, 1.0)
    for coordinate_axis in (axis.xaxis, axis.yaxis, axis.zaxis):
        coordinate_axis.pane.set_facecolor(pane_color)
        coordinate_axis.pane.set_edgecolor((1, 1, 1, 1))
        coordinate_axis._axinfo["grid"]["color"] = (1, 1, 1, 1)
        coordinate_axis._axinfo["grid"]["linewidth"] = 0.8

    axis.set_xlabel("x", fontsize=7, labelpad=-5)
    axis.set_ylabel("y", fontsize=7, labelpad=-5)
    axis.set_zlabel("z", fontsize=7, labelpad=-5)
    axis.tick_params(axis="both", labelsize=6, pad=-2)


def scatter_error_cloud(
    axis,
    points: np.ndarray,
    errors: np.ndarray,
    norm: Normalize,
) -> None:
    axis.scatter(
        points[:, 0],
        points[:, 1],
        points[:, 2],
        s=5.0,
        c=errors,
        cmap=BLACKBODY_NO_WHITE,
        norm=norm,
        edgecolors="#3b3b3b",
        linewidths=0.12,
        alpha=0.98,
        rasterized=True,
    )


def layout_columns(display: str) -> list[tuple[str, str]]:
    columns = [
        ("source", "Source PC"),
        ("target", "Target PC"),
    ]
    if display == "gpc":
        columns.append(("gpc_registered", "Registered (GPC-Reg)"))
    elif display == "deftransnet":
        columns.append(
            ("def_registered", "Registered (DefTransNet)")
        )
    else:
        columns.extend(
            [
                ("def_registered", "Registered (DefTransNet)"),
                ("gpc_registered", "Registered (GPC-Reg)"),
            ]
        )
    return columns


def errors_for_key(result: dict, point_key: str) -> np.ndarray:
    if point_key in ("source", "target"):
        return result["initial_errors"]
    if point_key == "def_registered":
        return result["def_errors"]
    if point_key == "gpc_registered":
        return result["gpc_errors"]
    raise KeyError(point_key)


def make_figure(
    results: list[dict],
    args: argparse.Namespace,
    output_path: Path,
) -> None:
    columns = layout_columns(args.display)
    column_count = len(columns)
    width = 12.2 if column_count == 3 else 15.0

    figure = plt.figure(figsize=(width, 11.2))
    grid = figure.add_gridspec(
        6,
        column_count,
        height_ratios=[1.0, 0.18, 1.0, 0.18, 1.0, 0.18],
        left=0.025,
        right=0.91,
        bottom=0.025,
        top=0.985,
        wspace=-0.03,
        hspace=0.14,
    )

    axes: list[list] = []
    all_error_arrays = []
    for result in results:
        for point_key, _ in columns:
            all_error_arrays.append(errors_for_key(result, point_key))
    global_max = float(
        np.max(np.concatenate(all_error_arrays, axis=0))
    )
    norm = Normalize(vmin=0.0, vmax=max(global_max, 1e-8), clip=True)

    point_keys = [key for key, _ in columns]
    all_points = np.concatenate(
        [
            result[point_key]
            for result in results
            for point_key in point_keys
        ],
        axis=0,
    )
    minimum = all_points.min(axis=0)
    maximum = all_points.max(axis=0)
    shared_centre = 0.5 * (minimum + maximum)
    shared_radius = max(
        0.53 * float(np.max(maximum - minimum)),
        1e-4,
    )

    row_letters = ("a", "b", "c")
    for row, result in enumerate(results):
        row_axes = []

        for column, (point_key, title) in enumerate(columns):
            axis = figure.add_subplot(
                grid[2 * row, column],
                projection="3d",
            )
            scatter_error_cloud(
                axis,
                result[point_key],
                errors_for_key(result, point_key),
                norm,
            )
            style_coordinate_axis(
                axis,
                shared_centre,
                shared_radius,
                args.elev,
                args.azim,
            )
            axis.set_title(title, fontsize=15, pad=5)
            row_axes.append(axis)
        axes.append(row_axes)

        label_axis = figure.add_subplot(grid[2 * row + 1, :])
        label_axis.set_xlim(0, 1)
        label_axis.set_ylim(0, 1)
        label_axis.axis("off")
        label_axis.text(
            0.5,
            0.72,
            (
                f"({row_letters[row]})  "
                f"Deformation level {result['level']:.1f}"
            ),
            ha="center",
            va="center",
            fontsize=15,
        )
        label_axis.plot(
            [0.01, 0.99],
            [0.22, 0.22],
            color="black",
            linewidth=1.3,
            clip_on=False,
        )

    scalar_map = ScalarMappable(
        norm=norm,
        cmap=BLACKBODY_NO_WHITE,
    )
    scalar_map.set_array([])
    colorbar_axis = figure.add_axes([0.925, 0.11, 0.017, 0.78])
    colorbar = figure.colorbar(
        scalar_map,
        cax=colorbar_axis,
    )
    colorbar.set_label(
        "Identity-specific point error",
        fontsize=13,
    )
    colorbar.ax.tick_params(labelsize=8)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_base = (
        output_path.with_suffix("")
        if output_path.suffix
        else output_path
    )
    pdf_path = output_base.with_suffix(".pdf")
    png_path = output_base.with_suffix(".png")
    figure.savefig(pdf_path, bbox_inches="tight")
    figure.savefig(png_path, dpi=260, bbox_inches="tight")
    plt.close(figure)

    print("\nSaved:")
    print(f"  {pdf_path}")
    print(f"  {png_path}")


def main() -> None:
    args = parse_args()

    gpc_script = resolved(args.gpc_script)
    if not gpc_script.is_file():
        raise FileNotFoundError(f"GPC-Reg script not found: {gpc_script}")

    gpc_module = evaluation.import_module_from_path(
        "gpcreg_registration_examples",
        gpc_script,
    )
    device = evaluation.configure_device(args.device, gpc_module)
    evaluation.set_all_seeds(42)

    selected_pairs = create_same_sample_pairs(args, gpc_module)

    deftransnet, gpc_reg = build_models(args, gpc_module, device)
    results = [
        register_pair(
            pair,
            deftransnet,
            gpc_reg,
            args,
            gpc_module,
            device,
        )
        for pair in selected_pairs
    ]

    print(f"Device: {device}")
    print(f"Display mode: {args.display}")
    for result in results:
        values = [
            f"{result['name']} level={result['level']:.1f}",
            f"initial={result['initial_errors'].mean():.6f}",
        ]
        if "def_mean" in result:
            values.append(f"DefTransNet={result['def_mean']:.6f}")
        if "gpc_mean" in result:
            values.append(f"GPC-Reg={result['gpc_mean']:.6f}")
        print("  " + " | ".join(values))

    make_figure(results, args, resolved(args.output))


if __name__ == "__main__":
    main()
